# Generated by Django 4.2.20 on 2025-03-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('short_description', models.CharField(max_length=128)),
                ('long_description', models.TextField()),
                ('product_image', models.ImageField(blank=True, default='', upload_to='products/%Y/%m')),
                ('price', models.FloatField()),
                ('promotional_price', models.FloatField()),
                ('product_type', models.CharField(choices=[('S', 'Simples'), ('V', 'Variável')], default=None, max_length=1)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
