# Generated by Django 4.2.20 on 2025-03-24 14:57

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='products/defaults/product_default.png', upload_to='products/%Y/%m', validators=[utils.validators.validate_image.is_png_svg]),
        ),
    ]
