# Generated by Django 4.2.20 on 2025-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default='', to='ecommerce.category'),
        ),
    ]
