# Generated by Django 4.2.20 on 2025-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Coloque quantos produtos tem em estoque.', null=True),
        ),
    ]
