# Generated by Django 4.2.20 on 2025-04-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=65)),
                ('product_id', models.PositiveBigIntegerField()),
                ('product_variation', models.CharField(max_length=65)),
                ('product_variation_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_amount', models.PositiveIntegerField()),
                ('imagem', models.CharField(max_length=2560)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido')),
            ],
        ),
    ]
