# Generated by Django 4.2.20 on 2025-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='product_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
