# Generated by Django 4.2.20 on 2025-04-07 19:07

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_itempedido_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_image',
            field=models.ImageField(blank=True, default='products/defaults/product_default.png', upload_to='products/%Y/%m', validators=[utils.validators.validate_image.is_png_svg]),
        ),
    ]
