# Generated by Django 4.2.20 on 2025-04-07 19:15

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_remove_product_name_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_image',
            field=models.ImageField(blank=True, default=None, upload_to='products/defaults/product_default.png', validators=[utils.validators.validate_image.is_png_svg]),
        ),
    ]
