# Generated by Django 4.2.20 on 2025-04-07 19:27

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_product_name_alter_productvariation_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotional_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('S', 'Simples'), ('V', 'Variável')], default=None, help_text='Produto "Simples" não possui variações, sendo ele único.<br>Já o produto "Variável" é um produto cujo possui variações, por exemplo, cores e tamanhos diferentes.', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Essa campo será preenchido conforme o estoque for preenchido. <br>Em variações, basta colocar quantos produtos.', null=True, verbose_name='Estoque total'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_image',
            field=models.ImageField(blank=True, default='products/defaults/product_default.png', upload_to='products/%Y/%m', validators=[utils.validators.validate_image.is_png_svg]),
        ),
    ]
