# Generated by Django 4.2.20 on 2025-04-11 14:53

from django.db import migrations, models
import utils.files.name_file
import utils.images.image_validator
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.files.name_file.get_file_name, validators=[utils.validators.validate_image.is_png_svg, utils.images.image_validator.resize_image]),
        ),
    ]
