# Generated by Django 4.2.20 on 2025-04-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_order_orderitem_remove_pedido_user_delete_itempedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, null=True, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('zip_code', models.CharField(max_length=10, null=True, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='ecommerce.userprofileadress', verbose_name='Endereço'),
        ),
    ]
