# Generated by Django 4.2.20 on 2025-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileadress',
            name='complement',
            field=models.CharField(default='', max_length=100),
        ),
    ]
