# Generated by Django 4.2.20 on 2025-04-11 16:30

from django.db import migrations, models
import utils.validators.validate_cpf


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_userprofileadress_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=11, null=True, validators=[utils.validators.validate_cpf.cpf_validator]),
        ),
    ]
