# Generated by Django 4.2.20 on 2025-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_alter_userprofile_birth_date_alter_userprofile_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totol_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
