# Generated by Django 4.2.20 on 2025-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_order_totol_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totol_items',
        ),
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
