# Generated by Django 4.2.20 on 2025-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_alter_productvariation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
