# Generated by Django 4.2.20 on 2025-03-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='E-commerce | Change-me', max_length=65)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=35)),
                ('contact_email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, default='', upload_to='logo/Y%/%m')),
                ('favicon', models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
