# Generated by Django 4.2.20 on 2025-03-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_socialmidialinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configuration'},
        ),
        migrations.AddField(
            model_name='socialmidialinks',
            name='socialmidiaicon',
            field=models.ImageField(blank=True, default='', upload_to='icon/%Y/%m'),
        ),
    ]
