# Generated by Django 4.2.20 on 2025-03-22 22:01

from django.db import migrations, models
import utils.validators.validate_image


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_alter_siteconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m', validators=[utils.validators.validate_image.is_png_svg]),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logo/Y%/%m', validators=[utils.validators.validate_image.is_png_svg]),
        ),
    ]
