services:
  application:
    container_name: application
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./application:/application
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - mysql_ecommerce_project

  mysql_ecommerce_project:
    container_name: mysql_ecommerce_project
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./dotenv_files/.env

volumes:
  mysql_data_ecommerce_project: